# docker-compose.yml
# We should let the IP address fixed, because the DNS do not work correctly when joining L1 nodes
version: '3'
services:
  l0-currency:
    container_name: l0-currency
    build: ../../images/currency-l0
    image: currency-l0
    environment:
      - CL_KEYSTORE=token-key.p12
      - CL_KEYALIAS=token-key
      - CL_PASSWORD=password
      - CL_PUBLIC_HTTP_PORT=9000
      - CL_P2P_HTTP_PORT=9001
      - CL_CLI_HTTP_PORT=9002
      - CL_GLOBAL_L0_PEER_HTTP_HOST=l0-global
      - CL_GLOBAL_L0_PEER_HTTP_PORT=9000
      - CL_GLOBAL_L0_PEER_ID=b1cf4d017eedb3e187b4d17cef9bdbcfdb2e57b26e346e9186da3a7a2b9110d73481fedbc6de23db51fb932371c54b02fff3388712dcb1e902870da7fa472f66
      - CL_APP_ENV=dev
      - CL_COLLATERAL=0
      - CL_L0_TOKEN_IDENTIFIER=DAG2Y1t8fbM9tN2GS2Vu8wh4vGGCjpRu796iNzcm
    volumes:
      - ../../shared/common_keys:/code/keys/
      - ../../shared/jars:/code/jars/
      - ../../images/currency-l0/tessellation:/code/codebase/tessellation
      - ../../images/currency-l0/genesis:/code/genesis/
    ports:
      - '9100:9000'
      - '9101:9001'
    networks:
      custom-network:
        ipv4_address: 172.50.0.3
    command: >
      sh -c "cp genesis/genesis.csv genesis.csv && \
             cp keys/token-key.p12 token-key.p12 && \
             cp currency-l0.jar jars/currency-l0.jar && \
             java -jar currency-l0.jar run-genesis genesis.csv --ip 172.50.0.3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://l0-currency:9000/cluster/info" ]
      interval: 10s
      timeout: 10s
      retries: 10
networks:
  custom-network:
    external: true