---
- name: Start data-l1 initial validator
  hosts: node-1
  gather_facts: false
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ data_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ data_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ data_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ lookup('env', 'P12_GENESIS_FILE_NAME') }}"
    CL_KEYALIAS: "{{ lookup('env', 'P12_GENESIS_FILE_KEY_ALIAS') }}"
    CL_PASSWORD: "{{ lookup('env', 'P12_GENESIS_FILE_PASSWORD') }}"
    
    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting data-l1 initial validator
      include_tasks: initial_validator.ansible.yml

    - name: Get node_id
      shell: |
        cd /home/{{ ansible_user }}/code/data-l1
        java -jar cl-wallet.jar show-id
      register: node_id
      ignore_errors: yes 

    - set_fact:
        dl1_node_1_ip: "{{ ansible_host }}"
        dl1_node_1_id: "{{ node_id.stdout }}"

- name: Start data-l1 validator 1
  hosts: node-2
  gather_facts: false
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ data_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ data_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ data_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ lookup('env', 'P12_NODE_2_FILE_NAME') }}"
    CL_KEYALIAS: "{{ lookup('env', 'P12_NODE_2_FILE_KEY_ALIAS') }}"
    CL_PASSWORD: "{{ lookup('env', 'P12_NODE_2_FILE_PASSWORD') }}"

    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting data-l1 validator 1 node
      include_tasks: validator.ansible.yml
      vars:
        DATA_L1_GENESIS_NODE_ID: "{{ hostvars['node-1']['dl1_node_1_id'] }}"
        DATA_L1_GENESIS_NODE_IP: "{{ hostvars['node-1']['dl1_node_1_ip'] }}"

- name: Start data-l1 validator 2
  hosts: node-3
  gather_facts: false
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ data_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ data_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ data_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ lookup('env', 'P12_NODE_3_FILE_NAME') }}"
    CL_KEYALIAS: "{{ lookup('env', 'P12_NODE_3_FILE_KEY_ALIAS') }}"
    CL_PASSWORD: "{{ lookup('env', 'P12_NODE_3_FILE_PASSWORD') }}"

    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting data-l1 validator 1 node
      include_tasks: validator.ansible.yml
      vars:
        DATA_L1_GENESIS_NODE_ID: "{{ hostvars['node-1']['dl1_node_1_id'] }}"
        DATA_L1_GENESIS_NODE_IP: "{{ hostvars['node-1']['dl1_node_1_ip'] }}"