---
- name: Check if data-l1.jar exists
  stat:
    path: "/home/{{ ansible_user }}/code/data-l1/data-l1.jar"
  register: data_l1_jar

- name: Display message if file data-l1.jar doesn't exist
  debug:
    msg: "File /home/{{ ansible_user }}/code/data-l1/data-l1.jar does not exist"
  when: not data_l1_jar.stat.exists

- name: Skip remaining tasks if file data-l1.jar doesn't exist
  meta: end_play
  when: not data_l1_jar.stat.exists
  
- name: Check if token file exists
  stat:
    path: "/home/{{ ansible_user }}/code/data-l1/{{ lookup('env', 'CL_KEYSTORE') }}"
  register: token_file

- name: Throw an error if the token_file doesn't exist
  fail:
    msg: "File /home/{{ ansible_user }}/code/data-l1/{{ lookup('env', 'CL_KEYSTORE') }} does not exist"
  when: not token_file.stat.exists

- name: Start as validator
  shell: |
    cd "/home/{{ ansible_user }}/code/data-l1"
    nohup java -jar data-l1.jar run-validator --ip {{ ansible_host }} > data-l1.log 2>&1 &

- name: Check if node is ReadyToJoin
  uri:
    url: "http://localhost:{{ data_l1_public_port }}/node/info"
    method: GET
    return_content: yes
  register: response
  until: response.status == 200 and ("ReadyToJoin" in response.content | string or retries >= 100)
  retries: 120
  delay: 1
  vars:
    retries: 0

- name: Join Cluster
  uri:
    url: "http://localhost:{{ data_l1_cli_port }}/cluster/join"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      id: "{{ DATA_L1_GENESIS_NODE_ID }}"
      ip: "{{ DATA_L1_GENESIS_NODE_IP }}"
      p2pPort: "{{ data_l1_p2p_port }}"
    return_content: yes
  register: curl_output
  until: (curl_output.status == 200 or curl_output.status == 404) or retries >= 5
  retries: 5
  delay: 10
  vars:
    retries: 0