---
- name: Check if currency-l1.jar exists
  stat:
    path: "/home/{{ ansible_user }}/code/currency-l1/currency-l1.jar"
  register: currency_l1_jar

- name: Display message if file currency-l1.jar doesn't exist
  debug:
    msg: "File /home/{{ ansible_user }}/code/currency-l1/currency-l1.jar does not exist"
  when: not currency_l1_jar.stat.exists

- name: Skip remaining tasks if file currency-l1.jar doesn't exist
  meta: end_play
  when: not currency_l1_jar.stat.exists
     
- name: Check if token file exists
  stat:
    path: "/home/{{ ansible_user }}/code/currency-l1/{{ lookup('env', 'CL_KEYSTORE') }}"
  register: token_file

- name: Throw an error if the token_file doesn't exist
  fail:
    msg: "File /home/{{ ansible_user }}/code/currency-l1/{{ lookup('env', 'CL_KEYSTORE') }} does not exist"
  when: not token_file.stat.exists

- name: Start as initial validator
  shell: |
    cd "/home/{{ ansible_user }}/code/currency-l1"
    nohup java -jar currency-l1.jar run-initial-validator --ip {{ ansible_host }} > currency-l1.log 2>&1 &

- name: Check if node is Ready
  uri:
    url: "http://localhost:{{ currency_l1_public_port }}/node/info"
    method: GET
    return_content: yes
  register: response
  until: response.status == 200 and ("Ready" in response.content | string or retries >= 100)
  retries: 120
  delay: 1
  vars:
    retries: 0