---
nodes:
  hosts:
    node-1:
      ansible_host: 52.24.83.103
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
