---
- name: Start currency-l1 initial validator
  hosts: node-1
  gather_facts: false
  vars:
     all_nodes: "{{ lookup('env', 'NODES') }}"
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ base_currency_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ base_currency_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ base_currency_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ base_metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ all_nodes[0].key_file.name }}"
    CL_KEYALIAS: "{{ all_nodes[0].key_file.alias }}"
    CL_PASSWORD: "{{ all_nodes[0].key_file.password }}"
    
    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting currency-l1 initial validator
      include_tasks: initial_validator.ansible.yml

    - name: Get node_id
      shell: |
        cd /home/{{ ansible_user }}/code/currency-l1
        java -jar cl-wallet.jar show-id
      register: node_id
      ignore_errors: yes 

    - set_fact:
        cl1_node_1_ip: "{{ ansible_host }}"
        cl1_node_1_id: "{{ node_id.stdout }}"

- name: Start currency-l1 validator 1
  hosts: node-2
  gather_facts: false
  vars:
     all_nodes: "{{ lookup('env', 'NODES') }}"
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ base_currency_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ base_currency_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ base_currency_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ base_metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ all_nodes[1].key_file.name }}"
    CL_KEYALIAS: "{{ all_nodes[1].key_file.alias }}"
    CL_PASSWORD: "{{ all_nodes[1].key_file.password }}"

    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting currency-l1 validator 1 node
      include_tasks: validator.ansible.yml
      vars:
        currency_L1_GENESIS_NODE_ID: "{{ hostvars['node-1']['cl1_node_1_id'] }}"
        currency_L1_GENESIS_NODE_IP: "{{ hostvars['node-1']['cl1_node_1_ip'] }}"

- name: Start currency-l1 validator 2
  hosts: node-3
  gather_facts: false
  vars:
     all_nodes: "{{ lookup('env', 'NODES') }}"
  environment:
    CL_PUBLIC_HTTP_PORT: "{{ base_currency_l1_public_port }}"
    CL_P2P_HTTP_PORT: "{{ base_currency_l1_p2p_port }}"
    CL_CLI_HTTP_PORT: "{{ base_currency_l1_cli_port }}"

    CL_L0_PEER_ID: "{{ ml0_node_1_id }}"
    CL_L0_PEER_HTTP_HOST: "{{ ml0_node_1_ip }}"
    CL_L0_PEER_HTTP_PORT: "{{ base_metagraph_l0_public_port }}"

    CL_GLOBAL_L0_PEER_ID: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_ID') }}"
    CL_GLOBAL_L0_PEER_HTTP_HOST: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_IP') }}"
    CL_GLOBAL_L0_PEER_HTTP_PORT: "{{ lookup('env', 'DEPLOY_NETWORK_HOST_PUBLIC_PORT') }}"

    CL_KEYSTORE: "{{ all_nodes[2].key_file.name }}"
    CL_KEYALIAS: "{{ all_nodes[2].key_file.alias }}"
    CL_PASSWORD: "{{ all_nodes[2].key_file.password }}"

    CL_APP_ENV: "{{ lookup('env', 'DEPLOY_NETWORK_NAME') }}"
    CL_COLLATERAL: 0
    CL_L0_TOKEN_IDENTIFIER: "{{ lookup('env', 'METAGRAPH_ID') }}"
  tasks:
    - name: Starting currency-l1 validator 1 node
      include_tasks: validator.ansible.yml
      vars:
        currency_L1_GENESIS_NODE_ID: "{{ hostvars['node-1']['cl1_node_1_id'] }}"
        currency_L1_GENESIS_NODE_IP: "{{ hostvars['node-1']['cl1_node_1_ip'] }}"