---
- import_playbook: clean.ansible.yml

- import_playbook: metagraph-l0/cluster.ansible.yml
  vars:
    force_genesis: "{{ force_genesis }}"

- name: Get metagraph L0 node info
  gather_facts: false
  hosts: node-1
  environment:
    CL_KEYSTORE: "{{ lookup('env', 'P12_NODE_1_FILE_NAME') }}"
    CL_KEYALIAS: "{{ lookup('env', 'P12_NODE_1_FILE_KEY_ALIAS') }}"
    CL_PASSWORD: "{{ lookup('env', 'P12_NODE_1_FILE_PASSWORD') }}"
  tasks:
    - name: Get node_id
      shell: |
        cd /home/{{ ansible_user }}/code/metagraph-l0
        java -jar cl-wallet.jar show-id
      register: node_id
      ignore_errors: yes 

    - set_fact:
        ml0_node_1_ip: "{{ ansible_host }}"
        ml0_node_1_id: "{{ node_id.stdout }}"

- import_playbook: currency-l1/cluster.ansible.yml
  vars:
    ml0_node_1_id: "{{ hostvars['node-1']['ml0_node_1_id'] }}"
    ml0_node_1_ip: "{{ hostvars['node-1']['ml0_node_1_ip'] }}"

- import_playbook: data-l1/cluster.ansible.yml
  vars:
    ml0_node_1_id: "{{ hostvars['node-1']['ml0_node_1_id'] }}"
    ml0_node_1_ip: "{{ hostvars['node-1']['ml0_node_1_ip'] }}"